### ISSUE TITLE
pax create hangs on macOS 12.5.1

### ISSUE THREAD

**Issue by GRVYDEV** [pax-lang/pax#3]
👋 Hey team. I am playing around with Pax and noticed that the CLI seems to not work properly. When I run `pax create new_project` the command just hangs until I terminate it with ctrl-c. Unfortunately I don't get any debug output. Here is my environment:
- macOS 12.5.1
- rustc 1.66.0
- cargo 1.66.0

Let me know if there is any other information that would be helpful!

**Comment by GRVYDEV** [comment]
Closing since I noticed this isn't implemented yet and the version of `pax-cli` currently on crates.io is stale. It may be worth updating once you feel it's ready to go :)

**Comment by zackbrown** [comment]
Thanks in any case for the report!  To get started on current master (unstable pre-alpha), i.e. [3682859](https://github.com/pax-lang/pax/commit/36828598d152a1afdbb7a5e18282f01ceb3f7853) —

1. Install dev deps specified at https://github.com/pax-lang/pax#development
2. clone repo, `cd pax/pax-example`
3. use the `pax` shell executable inside `pax-example` as a proxy for the CLI — e.g. `./pax run --target=macos`

That should get you rendering shapes on screen, but current master is broken in a number of ways, including ability to use control-flow (so e.g. `<Stacker>` doesn't work on master, because it uses `for` internally.)
